<?php 
/**
 * Implements hook_permission.
*/
function notifications_permission() {
	return array(
    	'access notifications' => array(
    		'title' => t('Allow user to grant themselves access to Notifications.'),
    	),      	
    );
}


/**
 * Implements hook_init.
*/
/*function notifications_init() {

}*/



/**
 * Implements hook_requirements().
 */
function notifications_requirements($phase) {
	$requirements = array();
  
	if ($phase == 'runtime') {
		$notifications_touched = variable_get('notifications_grant_access_touched', 0);
		if ( $notifications_touched == 0 ) {
			$requirements['site_name'] = array(
				'title' => 'Notifications',
				'description' => t('Notification permissions not accepted. Allow notifications ') . l('here', 'admin/config/content/notifications') . '.' ,
				'severity' => REQUIREMENT_WARNING,
				'value' => t('Disabled'),
			);
		} else {
			$requirements['site_name'] = array(
				'title' => 'Notifications',
				'description' => t('Notification permissions have been accepted. Modify ') . l('here', 'admin/config/content/notifications') . '.' ,
				'severity' => REQUIREMENT_OK,
				'value' => t('Enabled'),
			);
		}
	}
  
	return $requirements;
}


/**
 * Implements hook_page_alter.
*/
function notifications_page_alter(&$page) {
	$messages = drupal_get_messages(null, FALSE);
	
	if ( count( $messages ) ) {
		drupal_add_css(variable_get('messages_html_selector', '#console') . ' {display:none;}',
			array(
		        'group' => CSS_THEME,
		        'type' => 'inline',
		        'media' => 'screen',
		        'preprocess' => FALSE,
		        'weight' => '9999',
			)
		);
		
		$settings = array( 
			'messages' => $messages ,
			'path' => drupal_get_path('module', 'notifications'),
			'selector' => variable_get('messages_html_selector', '#console'), 
		);
		drupal_add_js(array('notifications' => $settings), 'setting');
		drupal_add_js(drupal_get_path('module', 'notifications') .'/js/notifications.js', 'file');
	}
}	


/**
 * Implements hook_admin.
*/
function notifications_admin() {
	$form = array();

	drupal_add_css(drupal_get_path('module', 'notifications') .'/css/notifications_admin.css');
	drupal_add_js(drupal_get_path('module', 'notifications') .'/js/notifications_admin.js');

	$form['notifications_grant_access'] = array(
		'#markup' => '<button type="button" id="edit-notifications-grant-access">Grant Access</button>',
	);
	
	$form['messages_html_selector'] = array(
		 '#type' => 'textfield', 
		 '#title' => t('Messages Selector'), 
		 '#default_value' => variable_get('messages_html_selector', '#console'), 
		 '#size' => 60,
	);
	
	$form['notifications_grant_access_touched'] = array(
		'#type' => 'hidden',
		'#default_value' => variable_get('notifications_grant_access_touched', 0),
		'#attributes' => array( 'id' => 'notifications-grant-access-touched' ),
	);
	
		
	
	return system_settings_form($form);
}



/**
 * Implements hook_menu.
*/
function notifications_menu() {
	
  	$items = array();

  	$items['admin/config/content/notifications'] = array(
    	'title' => 'Notifications Stettings',
    	'description' => 'Grant access to notifications for use with Drupals messaging system.',
    	'page callback' => 'drupal_get_form',
    	'page arguments' => array('notifications_admin'),
    	'access arguments' => array('access notifications'),
	);

	return $items;
}



/**
 * Private Functions
*/